# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ACH-Generator
version:      0.01
version_from: lib/ACH/Generator.pm
installdirs:  site
requires:
    ACH: 0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
